
export const dublrAddr = {
    // 1: Ethereum mainnet
    // 5: Goerli testnet
    
    // 137: Polygon mainnet
    // Deployed from git commit: eb50917365bbbb0d948efe656610c5abe06aa3d8
    137: "0x3D739A2db4F42632ca090a7a6713a9A62DB994C0",
    
    // 80001: Mumbai testnet
    80001: "0x20518b3443916A0A39093f6a12071Bff517Fb2E5"
};

export const dublrABI =
[
  'constructor(uint256 initialMintPrice_NWCPerDUBLR_x1e9, uint256 initialMintAmountDUBLR)',
  'event Approval(address indexed holder, address indexed spender, uint256 amount)',
  'event ApprovalInfo(address indexed holder, address indexed spender, uint256 oldAmount, uint256 newAmount)',
  'event ApprovalWithExpiration(address indexed holder, address indexed spender, uint256 amount, uint256 expirationTimestamp)',
  'event BuySellOrder(address indexed buyer, address indexed seller, uint256 priceNWCPerDUBLR_x1e9, uint256 amountBoughtDUBLRWEI, uint256 amountRemainingInOrderDUBLRWEI, uint256 amountSentToSellerNWCWEI, uint256 amountChargedToBuyerNWCWEI)',
  'event CancelSellOrder(address indexed seller, uint256 priceNWCPerDUBLR_x1e9, uint256 amountDUBLRWEI)',
  'event ListSellOrder(address indexed seller, uint256 priceNWCPerDUBLR_x1e9, uint256 amountDUBLRWEI)',
  'event Mint(address indexed buyer, uint256 priceNWCPerDUBLR_x1e9, uint256 amountSpentNWCWEI, uint256 amountMintedDUBLRWEI)',
  'event OwnerCall(bytes msgData)',
  'event RefundChange(address indexed buyer, uint256 refundedNWCWEI)',
  'event Transfer(address indexed sender, address indexed recipient, uint256 amount)',
  'event TransferInfo(address indexed spender, address indexed sender, address indexed recipient, uint256 amount)',
  'event Unpayable(address indexed seller, uint256 amountNWCWEI, bytes data)',
  'function DOMAIN_SEPARATOR() view returns (bytes32)',
  'function _owner_authorizeBurner(address addr, bool authorize)',
  'function _owner_authorizeMinter(address addr, bool authorize)',
  'function _owner_cancelAllSellOrders()',
  'function _owner_enableBuying(bool enable)',
  'function _owner_enableChangingAllowanceWithoutZeroing(bool enable)',
  'function _owner_enableEIP2612(bool enable)',
  'function _owner_enableERC1363(bool enable)',
  'function _owner_enableERC20(bool enable)',
  'function _owner_enableERC4524(bool enable)',
  'function _owner_enableMinting(bool enable)',
  'function _owner_enableSelling(bool enable)',
  'function _owner_enableTransferToContracts(bool enable)',
  'function _owner_enableUnlimitedAllowances(bool enable)',
  'function _owner_setDefaultAllowanceExpirationSec(uint256 allowanceExpirationSec)',
  'function _owner_setMinSellOrderValueNWCWEI(uint256 minValueNWCWEI)',
  'function _owner_setSellerPaymentFractionFixedPoint(uint256 paymentFractionFixedPoint)',
  'function allSellOrders() view returns (tuple(uint256 priceNWCPerDUBLR_x1e9, uint256 amountDUBLRWEI)[] priceAndAmountOfSellOrders)',
  'function allowance(address holder, address spender) view returns (uint256 amount)',
  'function allowanceWithExpiration(address holder, address spender) view returns (uint256 remainingAmount, uint256 expirationTimestamp)',
  'function approve(address spender, uint256 amount) returns (bool success)',
  'function approve(address spender, uint256 expectedCurrentAmount, uint256 amount) returns (bool success)',
  'function approveAndCall(address spender, uint256 amount) returns (bool success)',
  'function approveAndCall(address spender, uint256 amount, bytes data) returns (bool success)',
  'function approveWithExpiration(address spender, uint256 amount, uint256 expirationSec) returns (bool success)',
  'function balanceOf(address) view returns (uint256)',
  'function burn(uint256 amount)',
  'function burn(address addr, uint256 amount) returns (bool success)',
  'function buy(uint256 minimumTokensToBuyOrMintDUBLRWEI, bool allowBuying, bool allowMinting) payable',
  'function buyingEnabled() view returns (bool)',
  'function cancelMySellOrder()',
  'function cheapestSellOrder() view returns (tuple(uint256 priceNWCPerDUBLR_x1e9, uint256 amountDUBLRWEI) priceAndAmountOfSellOrder)',
  'function decimals() view returns (uint8)',
  'function decreaseAllowance(address spender, uint256 amountToSubtract) returns (bool success)',
  'function defaultAllowanceExpirationSec() view returns (uint256)',
  'function deposit(address addr, bytes depositData)',
  'function getStaticCallValues() view returns (tuple(bool buyingEnabled, bool sellingEnabled, bool mintingEnabled, uint256 blockGasLimit, uint256 balanceNWCWEI, uint256 balanceDUBLRWEI, uint256 mintPriceNWCPerDUBLR_x1e9, uint256 maxPriceNWCPerDUBLR_x1e9, uint256 minSellOrderValueNWCWEI, tuple(uint256 priceNWCPerDUBLR_x1e9, uint256 amountDUBLRWEI) mySellOrder, tuple(uint256 priceNWCPerDUBLR_x1e9, uint256 amountDUBLRWEI)[] allSellOrders) values)',
  'function increaseAllowance(address spender, uint256 amountToAdd) returns (bool success)',
  'function maxPriceNWCPerDUBLR_x1e9() view returns (uint256)',
  'function minSellOrderValueNWCWEI() view returns (uint256)',
  'function mint(address addr, uint256 amount) returns (bool success)',
  'function mintPrice() view returns (uint256 mintPriceNWCPerDUBLR_x1e9)',
  'function mintingEnabled() view returns (bool)',
  'function mySellOrder() view returns (tuple(uint256 priceNWCPerDUBLR_x1e9, uint256 amountDUBLRWEI) priceAndAmountOfSellOrder)',
  'function name() view returns (string)',
  'function nonces(address) view returns (uint256)',
  'function orderBookSize() view returns (uint256 numEntries)',
  'function permit(address holder, address spender, uint256 amount, uint256 deadline, uint8 v, bytes32 r, bytes32 s)',
  'function safeTransfer(address recipient, uint256 amount) returns (bool success)',
  'function safeTransfer(address recipient, uint256 amount, bytes data) returns (bool success)',
  'function safeTransferFrom(address holder, address recipient, uint256 amount) returns (bool success)',
  'function safeTransferFrom(address holder, address recipient, uint256 amount, bytes data) returns (bool success)',
  'function sell(uint256 priceNWCPerDUBLR_x1e9, uint256 amountDUBLRWEI)',
  'function sellerPaymentFractionFixedPoint() view returns (uint256)',
  'function sellingEnabled() view returns (bool)',
  'function supportsInterface(bytes4 interfaceId) view returns (bool supported)',
  'function symbol() view returns (string)',
  'function totalSupply() view returns (uint256)',
  'function transfer(address recipient, uint256 amount) returns (bool success)',
  'function transferAndCall(address recipient, uint256 amount) returns (bool success)',
  'function transferAndCall(address recipient, uint256 amount, bytes data) returns (bool success)',
  'function transferFrom(address holder, address recipient, uint256 amount) returns (bool success)',
  'function transferFromAndCall(address holder, address recipient, uint256 amount, bytes data) returns (bool success)',
  'function transferFromAndCall(address holder, address recipient, uint256 amount) returns (bool success)',
  'function underlying() view returns (address)',
  'function version() view returns (string)',
  'function withdraw(uint256 amount)'
];

